# Generated by Django 2.1.3 on 2018-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
